spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/PrimoDB
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl_auto: update
