spring:
    application:
        name: demoHalEx

    datasource:
        url: jdbc:mysql://127.0.0.1:3306/primodb
        username: root
        password:
    jpa:
        database: mysql
        shoe_sql: true
        hibernate:
            ddl-auto: create-drop

